### PR TITLE
Add ability to pass Search API Query options vias SearchAPISearch arguments

### PR DESCRIPTION
**Pull request by MurzNN**
Sometimes we need to pass specific custom options to Search API Query, for example to use `search_api_location` options ([example](https://www.drupal.org/project/jsonapi_search_api/issues/3094438)).
At now there are no ability to pass raw options to Search API Query via SearchAPISearch GraphQL function.

This PR adds the `options` argument, that can receive options and pass them to Search API Query.

Query example: 
```graphql
query {
  searchAPISearch(
    index_id: "geo_points"
   options: [
     {
       name: "search_api_location"
       json: "[{\"field\":\"geolocation\",\"lat\":56.304645,\"lon\":43.833524,\"radius\":50}]"
     }
   ],
    sort: {
      field: "geolocation", value: "ASC"
    }
  ) {
    result_count,
    documents {
      ... on GeoPointsDoc {
        id, label, geolocation
      }
    } 
  }
}
```

Please review it and comment, if something need to be reworked.

### CODE REVIEW

**Comment by MurzNN** [comment]
Soo, can anybody review my PR?

**Comment by duartegarin** [comment]
Hi @MurzNN ,
Thanks for the PR and apologies for the late reply, been pretty swamped lately.
This looks good, just wondering why you've added a composer.json file to the module? Doesn't seem necessary.
Cheers

**Comment by MurzNN** [comment]
@duartegarin About `composer.json` - I added it because most of other Drupal modules already have it, for better description in `composer` commands, and ability to set a requirements, if needed be.
For example, you can declare support of Drupal core versions via line like:
```
    "require": {
        "drupal/core": "^8.9 || ^9",
    },
```
If it is not needed, I can remove it.

**Comment by duartegarin** [comment]
I think that's sensible @MurzNN , merging.

**Pull request merged**
